title:  Gerineldo
tagline:  about programming myself
author:
  name: "Paul Le"
  twitter:  paululele

menu:
- {name: 'About', url: 'about.html'}
- {name: 'Writing', url: 'writing.html'}
- {name: 'Contact', url: 'contact.html'}

social:
- {icon: 'github', link: 'https://www.github.com/gerineldo'}
- {icon: 'envelope', link: 'dan.szeredy@gmail.com'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer


